column_limit: 80
indent_width: 1
align_args: false
use_tab: true
tab_width: 2
continuation_indent_width: 2
# spaces_before_call: 1
spaces_inside_table_braces: true
extra_sep_at_table_end: true
chop_down_table: true
break_after_functioncall_lp: false
break_before_functioncall_rp: false
single_quote_to_double_quote: true
keep_simple_function_one_line: false
keep_simple_control_block_one_line: false
