#!/usr/bin/env sh

#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)#configure-scripting-addition
#
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
sudo yabai --load-sa
#
yabai -m signal --add event=window_destroyed \
  action="yabai_focus_under_cursor"
yabai -m signal --add event=window_minimized \
  action="yabai_focus_under_cursor"
yabai -m signal --add event=application_hidden \
  action="yabai_focus_under_cursor"

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse off \
	window_origin_display default \
	window_placement second_child \
	window_zoom_persist on \
	window_topmost off \
	window_shadow on \
	window_animation_duration 0.0 \
	window_animation_frame_rate 60 \
	window_opacity_duration 1.0 \
	active_window_opacity 1.0 \
	normal_window_opacity 1.0 \
	window_opacity on \
	insert_feedback_color 0xffd75f5f \
	active_window_border_color 0xffc678dd \
	normal_window_border_color 0xff555555 \
	window_border_width 2 \
	window_border_radius 10 \
	window_border_blur on \
	window_border_hidpi on \
	window_border on \
	split_ratio 0.50 \
	split_type auto \
	auto_balance off \
	top_padding 4 \
	bottom_padding 4 \
	left_padding 4 \
	right_padding 4 \
	window_gap 4 \
	layout bsp \
	mouse_modifier fn \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# yabai -m space --create --label main
# yabai -m space --create --label dev
# yabai -m space --create --label entertain

# yabai -m space 1 --label main
# yabai -m space 2 --label dev
# yabai -m space 3 --label entertain

echo "yabai configuration loaded.."
