os:
  edit: "nvim" # as an example
gui:
  nerdFontsVersion: "3"
  authorColors:
    captainko: yellow

git:
  paging:
    colorArg: always
    # useConfig: true
    pager: delta --dark --paging=never --syntax-theme=gruvbox-dark
refresher:
  refreshInterval: 10
  fetchInterval: 45
