os:
  editCommand: "nvim" # as an example
gui:
  showIcons: true
  authorColors:
    captainko: yellow

git:
  paging:
    colorArg: always
    # useConfig: true
    pager: delta --dark --paging=never --syntax-theme=gruvbox-dark
