#!/bin/sh

cat <<EOF
endpoint: https://ttekvn.atlassian.net
login: thong.nguyen@ttekglobal.com
authentication-method: api-token
custom-commands:
  - name: sprint
    help: display issues for active sprint
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if $(project: ...) configured just list the issues for current project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved and project=$JIRA_PROJECT ORDER BY rank asc, created"
      else
          # otherwise list issues for all project
          {{jira}} list --template table --query "sprint in openSprints() and type != epic and resolution = unresolved ORDER BY rank asc, created"
      fi

  - name: mine
    help: display issues assigned to me
    script: |-
      if [ -n "$JIRA_PROJECT" ]; then
          # if $(project: ...) configured just list the issues for current project
          {{jira}} list --query "resolution = unresolved AND assignee=currentuser() AND project = $JIRA_PROJECT AND issuetype IN (sub-bug,sub-task) ORDER BY created,priority"
      else
          # otherwise list issues for all project
          {{jira}} list --query "resolution = unresolved AND assignee=currentuser() AND issuetype IN (sub-bug,sub-task) ORDER BY ORDER BY updated,created,priority"
      fi
EOF

# vim: filetype=sh :
