#!/bin/bash

# shortcuts lists
s_list=(

	# ==============================================================================
	# Code
	# ==============================================================================

	"7:$HOME/code/Projects/quany7a/"
	"7a:$HOME/code/Projects/quany7a/api/"
	"a:$HOME/code/Projects/clubv/Server/api/"
	"at:$HOME/code/node_projects/angular-test"
	"go:$HOME/code/go_projects/"
	"pg:$HOME/code/psg_project/learning"
	"no:$HOME/code/node_projects/notion-ts"
	"w:$HOME/code/Projects/Horizon/src/web/WebHorizon"

	# ==============================================================================
	# Sources
	# ==============================================================================

	"sr:$HOME/.local/src"

	# ==============================================================================
	# Documents
	# ==============================================================================

	"doc:$HOME/Documents"
	"eb:$HOME/Documents/ebooks/"
	"l:$HOME/Documents/Latex"
	"or:$HOME/Documents/org"
	"q:$HOME/Documents/queries"

	# ==============================================================================
	# dot files
	# ==============================================================================

	"d:$HOME/.dotfiles"
	"n:$HOME/.local/src/neovim"
	"s:$HOME/.scripts/"
	"v:$HOME/.config/nvim"
)

# Loop over shortcuts
for s in "${s_list[@]}"; do
	# check sub-list if available
	if [[ $s == *":"* ]]; then
		prefix="${s%:*}"
		suffix="${s#*:}"

		# e.g ze="cd ~/example"
		alias "z$prefix=cd $suffix"
	fi
done
