#!/bin/bash

# shortcuts lists
s_list=(
	# ==============================================================================
	# Code
	# ==============================================================================

	'7:~/code/Projects/quany7a/'
	'7a:~/code/Projects/quany7a/api/'
	'a:~/code/Projects/clubv/Server/api/'
	'at:~/code/node_projects/angular-test'
	'go:~/code/go_projects/'
	'pg:~/code/psg_project/learning'
	'no:~/code/node_projects/'
	'w:~/code/Projects/Horizon/src/web/WebHorizon'
	'plb:~/code/Projects/ltv/pmc-hrm/packages/backend'
	'plf:~/code/Projects/ltv/pmc-hrm/packages/frontend'

	# ==============================================================================
	# Sources
	# ==============================================================================

	'sr:~/.local/src'

	# ==============================================================================
	# Documents
	# ==============================================================================

	'doc~/Documents'
	'eb:~/Documents/ebooks/'
	'l:~/Documents/Latex'
	'or:~/Documents/org'
	'q:$~/Documents/queries'

	# ==============================================================================
	# Dotfiles
	# ==============================================================================

	'd:~/.dotfiles'
	'n:~/.local/src/neovim'
	's:~/.scripts/'
	'v:~/.config/nvim'
)

# Loop over shortcuts
for s in "${s_list[@]}"; do
	# check sub-list if available
	if [[ $s == *":"* ]]; then
		prefix="${s%:*}"
		suffix="${s#*:}"

		# e.g ze="cd ~/example"
		alias "z$prefix=cd $suffix"
	fi
done
