#!/bin/bash

set -euo pipefail

DMENU_ARGS=("$@")

SOUND_DIR="$HOME/.scripts/data/asounds"
SOUND_FILES=$(find "$SOUND_DIR" -iname "*.mp3" -printf "%f\n")

TITLE="ambient-sound"

function play_sound() {
	title="$1"
	file="$2"

	mpv --title="$title" --loop "$SOUND_DIR/$file" >/dev/null 2>&1 &

	SELECTED_SOUNDS+=("$file")
}

SELECTED_SOUNDS=()
function select_sound() {
	# echo "${SELECTED_SOUNDS[@]}"
	# list=("$(printf '%s\n' "${sound[@]}")")
	# echo "${list[@]}"
	# echo "${sound_file[@]}"
	# concated_sounds=("${SOUND_FILES[@]}" "${list[@]}")
	# join_selected_sounds=$(
	# 	SAVE_IFS="$IFS"
	# 	IFS=$'\n'
	# 	echo "${SELECTED_SOUNDS[*]}"
	# 	IFS="$SAVE_IFS"
	# )
	# # concat_sounds=("${SELECTED_SOUNDS[@]}" "${join_selected_sounds[@]}")
	# concat_sounds+=("${SELECTED_SOUNDS[@]}")
	# concat_sounds+=("${join_selected_sounds[@]}")
	# echo "$SOUND_FILES"
	sound_file=$(
		echo "${SOUND_FILES[@]}" | uniq -u |
			sort |
			dmenu -i -l 20 -p 'Choose sound file:' "${DMENU_ARGS[@]}"
	)

	play_sound "$TITLE - $sound_file" "$sound_file"

}

function open_menu() {

	opt_choose_a_sound="Choose a sound file"
	opt_play_rand="Play random sound"
	opt_stop_player="Stop sound player"
	# OPT_STOP_A_SOUND="Stop a sound"
	opt_quit="Quit"

	opts="$opt_choose_a_sound
$opt_play_rand
$opt_stop_player
$opt_quit"

	selected_opt=$(echo "$opts" | dmenu -i -l 7 -p 'Ambient sounds:' "${DMENU_ARGS[@]}")

	# If user chooses a sound file.
	if [ "$selected_opt" == "$opt_choose_a_sound" ]; then
		select_sound

	# If user chooses to play a random sound.
	elif [ "$selected_opt" == "$opt_play_rand" ]; then
		rand_file=$(echo "$SOUND_FILES" | shuf -n 1)
		# mpv --title="$TITLE - $RAND_FILE" --loop "$SOUND_DIR/$RAND_FILE" || exit
		play_sound "$TITLE - $rand_file" "$rand_file"

	# If user chooses to stop sound playing.
	elif [ "$selected_opt" == "$opt_stop_player" ]; then
		pkill -f "$TITLE"

	# elif [ "$opt" == "$OPT_STOP_A_SOUND" ]; then
	# 	pkill -f "$TITLE"

	# What to do if we just escape without choosing anything.
	else
		echo "Program terminated."
		exit
	fi

}

while :; do
	open_menu
done
