#!/bin/bash

get_summary() {
	code=$1
	summary=$(
		curl --silent "https://ttekvn.atlassian.net/rest/api/latest/issue/$code" \
			--user "$ATLASSIAN_EMAIL:$ATLASSIAN_TOKEN" |
			jq -r '.fields.summary'
	)
	echo "$summary"
}

pids=()
IFS='
'
for lines in $(git bv-last-month); do

	issue_codes=$(echo "$lines" | grep -oP "BV2-\d+")

	for code in $issue_codes; do
		get_summary "$code" &
		pids+=($!)
	done

done

wait "${pids[@]}"
