#!/bin/sh

if [ -z "$REPO_ROOT_DIR" ]; then
	REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
fi
result=$(
	{
		# TODO: faster way for this
		# only use git grep on modified files
		git diff --cached --name-only --diff-filter=CMR |
			sed -e 's/ /\\ /g' -e "s;.*;$REPO_ROOT_DIR/&;" |
			xargs --no-run-if-empty -I {} git grep --line-number --column --cached "\sDISCARD:" {}

		# use grep for new added file
		git diff --cached --name-only --diff-filter=A |
			sed -e 's/ /\\ /g' -e "s;.*;$REPO_ROOT_DIR/&;" |
			xargs -r -I {} grep --with-filename --line-number -e "\sDISCARD:" {}

	}
)

if [ -n "$result" ]; then
	echo "DISCARD these lines before committing"
	echo "$result"
	exit 1
fi

exit $?
