#!/bin/sh

if [ -z "$REPO_ROOT_DIR" ]; then
	REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"
fi
# echo $(git diff --cached --diff-filter=ACMR)
result=$(
	git grep --line-number --column --cached "DISCARD:" $(git diff --cached --name-only)
)

if [ -n "$result" ]; then
	echo "DISCARD these lines before committing"
	echo "$result"
	exit 1
fi

exit $?
