#!/bin/sh

DOWNLOAD_PATH=~/Downloads
EBOOK_PATH=~/Documents/EBOOK_PATH/
EPUB_PATH="$EBOOK_PATH"/epub
PDF_PATH="$EBOOK_PATH"/pdf
ISO_PATH=~/Downloads/ISO

[ ! -f "$EPUB_PATH" ] && mkdir -p "$EPUB_PATH"
[ ! -f "$PDF_PATH" ] && mkdir -p "$PDF_PATH"
[ ! -f "$ISO_PATH" ] && mkdir -p "$ISO_PATH"

find "${DOWNLOAD_PATH}" -maxdepth 1 -type f -name "*(Z-Library).pdf" \
	-exec mv -t "${PDF_PATH}" {} +
find "${DOWNLOAD_PATH}" -maxdepth 1 -type f -name "*.epub" \
	-exec mv -t "${EPUB_PATH}" {} +
find "${DOWNLOAD_PATH}" -maxdepth 1 -type f -name "*.iso" \
	-exec mv -t "${ISO_PATH}" {} +

# remove old-ass files

find "$DOWNLOAD_PATH" -maxdepth 1 -type f -atime +30 -delete
